### ISSUE TITLE
hexagon logo for EasyClimate

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [VeruGHub/easyclimate#25]
Hello, 
I was wondering if the team is interested in a free design R hexagon logo icon design by me. I am trying to build a portfolio and so far, team Terra package has accepted my free help. My name is Zane Dax and want to help out. If interested let me know. Thank you. 

---
Hola,
Me preguntaba si el equipo está interesado en un diseño de icono de logotipo hexagonal R gratuito de mi parte. Estoy tratando de crear una cartera y, hasta ahora, el paquete del equipo Terra ha aceptado mi ayuda gratuita. Mi nombre es Zane Dax y quiero ayudar. Si está interesado, hágamelo saber. Gracias.

**Comment by VeruGHub** [comment]
Hi Zane! Thanks for your proposal! As you see we do not have a logo so I would be very pleased if you could help us and design one. Let me know if you are still interested and how can we go ahead.

**Comment by PythonCoderUnicorn** [comment]
Hello VeruGHub,

Thank you for replying, yes I am still interested. I already have a design made. You can see the design using the link. I would be happy to make modifications if you like, hope you like it and if so, I will upload the full size image.

[EasyClimate Logo](https://www.figma.com/file/H1BlWP1aDZKLlmnT5g73mw/EasyClimate-Logo?node-id=0%3A1)

**Comment by VeruGHub** [comment]
Hi Zane,
Thanks for the logo. I love the "easy button". I have been thinking about the sticker and I would like to reflect somehow that the package deals with spacial climatic information. Some ideas are to include pixelated background representing different values of a raster map or to use a pin representing a location. For example: https://thenounproject.com/term/climate/3968723. Also, a logo with a thermometer would be more accurate than with the sun :) For example: https://thenounproject.com/term/weather-conditions/247168. I think I would remove the barplot since it is not so directly linked to the package.
Finally, in relation to the colors, I like the blue + white combination that you chose but I don't like the pink. Maybe you could use orange tones instead or just blue and white? I don't really know.
Thanks again for your initiative!

**Comment by PythonCoderUnicorn** [comment]
Hello VeruGHub,

I made modifications and looked at the icons from the links you shared and have implemented them in the updated designs. I removed the red / pink background and provided options of background along with icons.

hope you like them. 
[Updated designs](https://www.figma.com/file/H1BlWP1aDZKLlmnT5g73mw/EasyClimate-Logo?node-id=0%3A1)

**Comment by VeruGHub** [comment]
Hi Zane, I did a fast survey among some of the co-authors of the package and the most agreed solution is the one in the first column and second row. Is there any way that we can use to invite you a "virtual beer/soda" at least? (e.g. https://www.buymeacoffee.com/)

**Comment by PythonCoderUnicorn** [comment]
Hello VeryGHub,

Here is the first column, second row hexagon logo (size 941 x 1095).
Thank you for this opportunity, sincerely Zane Dax

As for the buymeacoffee, I don't have one fully set up, but thank you. 

![Easy Climate logo 9](https://user-images.githubusercontent.com/55933131/128714999-7a2bc59c-2980-4b9c-ad38-efd310ab7bca.png)

**Comment by VeruGHub** [comment]
Thank you, Zane!!
